version: '3'

services:
  app:
    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode

    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update VARIANT to pick a python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
      - db
    
    links: 
      - db
    
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cc
